### ISSUE TITLE
Can not find getShadowQueueContent() in DropShadowFilter.java  (JME 3.1)

### ISSUE THREAD

**Issue by Ali-RS** [jMonkeyEngine-Contributions/zay-es#7]
In example project MonkeyTrap
DropShadowFilter : https://github.com/jMonkeyEngine-Contributions/zay-es/blob/master/examples/MonkeyTrap/src/trap/filter/DropShadowFilter.java

error in this [line](https://github.com/jMonkeyEngine-Contributions/zay-es/blob/master/examples/MonkeyTrap/src/trap/filter/DropShadowFilter.java#L166) and this [line](https://github.com/jMonkeyEngine-Contributions/zay-es/blob/master/examples/MonkeyTrap/src/trap/filter/DropShadowFilter.java#L180)
`GeometryList casters = rq.getShadowQueueContent(ShadowMode.Cast);`

**Comment by pspeed42** [comment]
This filter needs to be reworked.  I thought I'd already fixed this one but I guess not.

As I recall, the fix is to keep a local field:
    private GeometryList casters;
...then at the end of initFilter()
        // Set our custom comparator for shadow casters
        casters = new GeometryList(new CasterComparator());

...then at the beginning of postFrame():
        RenderQueue rq = viewPort.getQueue();
        for (Spatial scene : viewPort.getScenes()) {
            ShadowUtil.getGeometriesInCamFrustum(scene, viewPort.getCamera(), ShadowMode.Cast, casters);
        }
        
        if( casters.size() == 0 ) {
            return;
        }

...and at the end of postFrame():
        casters.clear();

Something like that... if you want to make a patch.  Else I'm not sure when I will get to it.    I need to add a proper version of the drop shadow filter to SimFX sometime.
